- hosts: webservers
  become: yes

  vars:
    client_name: "client"

  tasks:
    - name: Copying easy-rsa to openvpn directory
      copy:
        src: /usr/share/easy-rsa/
        dest: /etc/openvpn/
        remote_src: yes

    - name: Create vars file
      copy:
        src: /etc/openvpn/vars.example
        dest: /etc/openvpn/vars
        remote_src: yes

    - name: Create server configuration file
      template:
        src: templates/server_config.j2
        dest: /etc/openvpn/server/server.conf

    - name: Initialize the PKI with Easy-RSA
      command: ./easyrsa init-pki
      args:
        chdir: /etc/openvpn

    - name: Building the CA certificate with expect
      expect:
        command: ./easyrsa build-ca nopass
        responses:
          ".*Common Name.*": ""
      args:
        chdir: /etc/openvpn

    # Server certificate generation
    - name: Generating server certificate request
      expect:
        command: ./easyrsa gen-req server nopass
        responses:
            ".*Common Name.*": ""
      args:
        chdir: /etc/openvpn

    - name: Sign server certificate with Easy-RSA
      expect:
        command: ./easyrsa sign-req server server
        responses:
          ".*Confirm request details.*": "yes"
      args:
        chdir: /etc/openvpn

    # Client certificate generation
    - name: Generating client certificate request
      expect:
        command: ./easyrsa gen-req {{ client_name }} nopass
        responses:
            ".*Common Name.*": ""
      args:
        chdir: /etc/openvpn

    - name: Sign client certificate with Easy-RSA
      expect:
        command: ./easyrsa sign-req {{ client_name }} client
        responses:
          ".*Confirm request details.*": "yes"
      args:
        chdir: /etc/openvpn

    - name: Generating the dh & ta certificates
      command: "{{ item }}"
      loop:
        - ./easyrsa gen-dh
        - openvpn --genkey secret ta.key
      args:
        chdir: /etc/openvpn

    - name: Copying ca.crt dh.pem server.crt server.key file
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
      loop:
        - { src: '/etc/openvpn/pki/ca.crt', dest: '/etc/openvpn/' }
        - { src: '/etc/openvpn/pki/dh.pem', dest: '/etc/openvpn/' }
        - { src: '/etc/openvpn/pki/issued/server.crt', dest: '/etc/openvpn/' }
        - { src: '/etc/openvpn/pki/private/server.key', dest: '/etc/openvpn/' }

  handlers:
    - name: Reload UFW
      command: ufw reload

    - name: Stop OpenVPN
      command: systemctl stop openvpn.service
      
    - name: Reload OpenVPN
      command: systemctl reload openvpn.service
